# Generated by Django 4.0 on 2022-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mall id')),
                ('mall_name', models.CharField(max_length=150, verbose_name='Mall title')),
                ('addr_street', models.CharField(max_length=150, verbose_name='Street name')),
                ('addr_housenumber', models.CharField(max_length=20, verbose_name='House number')),
                ('building_lvl', models.PositiveSmallIntegerField(default=1, verbose_name='Building levels')),
                ('image_link', models.SlugField(max_length=255, unique=True, verbose_name='Mall image link')),
            ],
            options={
                'verbose_name': 'Mall',
                'verbose_name_plural': 'Malls',
            },
        ),
    ]
