# Generated by Django 4.0 on 2022-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mall_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='image_link',
            field=models.CharField(max_length=25555, unique=True, verbose_name='Mall image link'),
        ),
    ]
