# Generated by Django 4.0 on 2022-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mall_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='building_lvl',
            new_name='building_levels',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='mall_name',
        ),
        migrations.AddField(
            model_name='mall',
            name='geometry',
            field=models.TextField(default='None', verbose_name='Geometry'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='addr_street',
            field=models.CharField(max_length=150, verbose_name='Mall title'),
        ),
    ]
