# Generated by Django 4.0 on 2022-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_building_lvl_mall_building_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='name',
            field=models.TextField(default='None', verbose_name='Mall name'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='addr_street',
            field=models.CharField(max_length=150, verbose_name='Mall Street Address'),
        ),
    ]
