# Generated by Django 4.0 on 2022-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mall_name_alter_mall_addr_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='addr_housenumber',
            field=models.TextField(max_length=20, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='addr_street',
            field=models.TextField(max_length=150, verbose_name='Mall Street Address'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='building_levels',
            field=models.TextField(default=1, verbose_name='Building levels'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Mall id'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='image_link',
            field=models.TextField(max_length=25555, unique=True, verbose_name='Mall image link'),
        ),
    ]
