# Generated by Django 4.0 on 2022-05-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_nodes_rename_mall_places_alter_places_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes',
            old_name='node_geometry',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='place_name',
            new_name='name',
        ),
    ]
