# Generated by Django 4.0 on 2022-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_node_geometry_nodes_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150, verbose_name='Shop name')),
                ('shop_link', models.TextField(max_length=25555, unique=True, verbose_name='Shop image link')),
                ('mall_id', models.IntegerField(verbose_name='Mall id')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
