# Generated by Django 4.0 on 2022-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='branch_id',
            field=models.IntegerField(default=1, verbose_name='Branch id'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.IntegerField(default=1, verbose_name='Shop id'),
        ),
    ]
