# Generated by Django 4.0 on 2022-05-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_shop_branch_id_shop_shop_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('shop_id', 'branch_id')},
        ),
    ]
