# Generated by Django 4.0 on 2022-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_shop_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Shop id'),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('id', 'branch_id')},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_id',
        ),
    ]
