# Generated by Django 4.0 on 2022-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_shop_unique_together_alter_shop_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Product id')),
                ('title', models.CharField(max_length=150, verbose_name='Product title')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('category', models.CharField(max_length=100, verbose_name='Product category')),
                ('image_link', models.TextField(max_length=25555, unique=True, verbose_name='Shop image link')),
                ('mall_id', models.IntegerField(verbose_name='Mall id')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='branch_id',
        ),
    ]
