# Generated by Django 4.0 on 2022-05-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_mall_id_product_shop_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='main_product',
        ),
    ]
